# Site settings
title: To be a better RanGo
description: serious sincerely positive insistent 
url: "http://liuwenran.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Wenran Liu
  bio      : A man who is a single dog
  email    : not_here@gmail.com
  twitter  : I have no twitter #https://twitter.com/mateussousam

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL
twitter_username: liuwenran # Twitter username
facebook:
    app_id: 0 # App ID
    publisher: 0# URL of the Facebook page
    admins: 0 # Facebook user ID that manages the page

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed